name: Deployment CI&CD

on:
  push:
    branches: ['main']

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            $env.PATH = '/home/ubuntu/.local/share/mise/installs/node/22/bin:/home/ubuntu/.local/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/linuxbr
            ew/.linuxbrew/bin:/opt/homebrew/bin:/usr/local/go/bin:/opt/local/bin:/home/ubuntu/.bun/bin:/home/ubuntu/.cargo/bin:/home/ubuntu/.composer/vendor/bin:/home/ubuntu/.dvm:/home/ubuntu/.local/share/pnpm:/home/ubuntu/.
            yarn/bin:/home/ubuntu/Library/pnpm:/home/ubuntu/go/bin:/home/ubuntu/Library/Python/3.9/bin';

            # node options
            $env.NODE_OPTIONS = "--max-old-space-size=8192";

            # Setup (workdir + update repo)
            cd ~/jonasleonhard.de;
            git pull;

            # Build
            bun install;
            bun run build;
            sudo rsync -av --delete build/* /var/www/html/jonasleonhard.de;
